services:
  - type: web
    name: yemen-jobs-rss-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        fromService:
          type: web
          name: yemen-jobs-rss-bot
          property: port
      - key: TOKEN
        sync: false
      - key: MANAGER
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yemen-jobs-db
          property: connectionString
    healthCheckPath: /
    buildCommand: "echo 'Build completed'"
    startCommand: "python -u telegramRSSbot.py"

databases:
  - name: yemen-jobs-db
    databaseName: yemen_jobs_rss
    user: yemen_jobs_user
    plan: free
