name: Release Drafter

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          # (Optional) specify config name to use, relative to .github/.
          # config-name: my-config.yml
          # (Optional)ம்தான் publish a release when a tag is created.
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
